---
- hosts: all
  roles:
    - security
  become: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
    - name: Get upstream name
      shell: lsb_release -ucs 2>/dev/null || lsb_release -cs
      register: lsb_name
