---
- name: Check if Docker installed
  shell: "which docker"
  register: docker_is_installed
  failed_when: docker_is_installed.rc > 1

- name: Secure SSH
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^#?PasswordAuthentication", line: "PasswordAuthentication no" }
    - { regexp: "^#?PermitEmptyPasswords", line: "PermitEmptyPasswords no" }
    - { regexp: "^#?PermitRootLogin", line: "PermitRootLogin no" }
  notify: Restart SSH daemon
  become: yes

- name: Install Firewall
  package:
    name: ufw
    state: latest
  become: yes

- name: Disable firewall
  ufw:
    state: disabled
  become: yes

- name: Reset firewall configuration
  ufw:
    state: reset
  become: yes

- name: Clear out all iptables rules
  shell: iptables -F && iptables -X
  become: yes

- name: Enable forward policy
  lineinfile:
    dest: /etc/default/ufw
    regexp: '^#?DEFAULT_FORWARD_POLICY'
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'
  become: yes

- name: Deny incoming traffic by default
  ufw:
    policy: deny
    direction: incoming
  become: yes

- name: Allow outgoing traffic by default
  ufw:
    policy: allow
    direction: outgoing
  become: yes

- name: Allow ssh
  ufw:
    rule: allow
    port: '22'
    proto: tcp
  become: yes

- name: Allow Samba
  ufw:
    rule: allow
    app: "{{item}}"
  with_items: "{{firewall_allowed_apps}}"
  become: yes

- name: Rate limit SSH
  ufw:
    rule: limit
    port: ssh
    proto: tcp
  become: yes

- name: Configure ufw before rules for docker
  blockinfile:
    path: /etc/ufw/before.rules
    insertbefore: '^\*filter'
    block: |
      *nat
      :POSTROUTING ACCEPT [0:0]
      -A POSTROUTING ! -o docker0 -s 172.17.0.0/16 -j MASQUERADE
      COMMIT
  when: docker_is_installed.rc == 0
  become: yes

- name: Enable firewall
  ufw:
    state: enabled
  become: yes
