---
- name: Install Samba
  package:
    name: samba
    state: latest
  become: yes

- name: Add Samba users to Samba group
  user:
    name: "{{item.name}}"
    create_home: no
    groups: "sambashare"
    append: yes
  with_items: "{{secrets.samba_users}}"
  become: yes

- name: Create Samba users
  shell: "(echo {{item.password}}; echo {{item.password}}) | smbpasswd -s -a {{item.name}}"
  with_items: "{{secrets.samba_users}}"
  notify: Restart Samba
  become: yes
