---
- name: Add repositories
  apt_repository:
    repo: "{{item}}"
    state: present
  become: yes
  with_items: "{{repositories}}"

- name: Install packages
  package:
    name: "{{item}}"
    state: latest
  with_items: "{{packages}}"
  become: yes

- include: videos.yml
- include: samba.yml
